name: odoosaleapp
description: odoo sale application
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  flutter_cached_pdfview: ^0.4.3
  dropdown_search: ^5.0.3
  cached_network_image: ^3.2.3
  http: ^1.0.0
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.13.1
  keyboard_actions: ^4.2.0
  carousel_slider: ^5.0.0
  another_flushbar: ^1.12.30
  intl: ^0.18.1
  url_launcher: ^6.1.7
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  printing: ^5.13.2
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.1
  email_validator: ^3.0.0

flutter_native_splash:
  color: "#ffffff"        # Arka plan rengi
  image: assets/splash/splashlogo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/icon/iconlogo.png
    - assets/splash/splashlogo.png
    - assets/shopping_cart_.jpg
    - assets/shopping_cart.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconlogo.png"


